<?php
/**
 * Created by PhpStorm.
 * User: damai
 * Date: 2019/3/27
 * Time: 13:24
 */

namespace App\Http\Middleware;
use Closure;
use Illuminate\Cookie\Middleware\EncryptCookies as BaseEncrypter;

class IsLogin extends BaseEncrypter
{

    public function handle($request, Closure $next)
    {

        $userinfo = $request->session()->get('userinfo');

        if (!$userinfo){
           return redirect('admin/login/index');
        }

        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }

}