<?php
/**
 * Created by PhpStorm.
 * User: damai
 * Date: 2019/3/27
 * Time: 14:31
 */

namespace App\Http\Middleware;

use Closure;
use Illuminate\Cookie\Middleware\EncryptCookies as BaseEncrypter;

class Log extends BaseEncrypter
{

    public function handle($request, Closure $next)
    {


        dump($request->server());
        dump($request->all());
//        $url = $request->server('HTTP_REFERER');
//        $host = $request->server('HTTP_HOST');
//        dump($url);
//        dump($host);
//        $url = str_replace($host,'',$url);
//
//        dump($url);

        \App\Models\Backend\Log::addTable($request);


        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }

}