<?php
/**
 * Created by PhpStorm.
 * User: damai
 * Date: 2019/3/27
 * Time: 14:31
 */

namespace App\Http\Middleware;

use App\Models\Backend\menu\Node;
use Closure;
use Illuminate\Cookie\Middleware\EncryptCookies as BaseEncrypter;

class Log extends BaseEncrypter
{

    public function handle($request, Closure $next)
    {

//       $user_id = $request->session()->get('userinfo')->menus_id;
////
////        $url = $request->route()->getAction();
////
////        $a = Node::getDataByUrl($url['controller'],$user_id);
////
////       if (!$a){
////           return false;
////       }

        \App\Models\Backend\Log::addTable($request);


        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }

}